name: car_rental
description: A new Flutter application.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  flutter_swiper:
  flutter_country_picker:
  pin_code_fields:
  provider:
dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
  assets:
    - assets/
    - assets/images/

  fonts:
    - family: sanfra
      fonts:
        - asset: assets/fonts/SF-UI-Display-Regular.otf
    - family: Montserrat-Black
      fonts:
        - asset: assets/font_mon/Montserrat-Black.ttf

    - family: Montserrat-Bold
      fonts:
        - asset: assets/font_mon/Montserrat-Bold.ttf

    - family: Montserrat-ExtraLight
      fonts:
        - asset: assets/font_mon/Montserrat-ExtraLight.ttf

    - family: Montserrat-Medium
      fonts:
        - asset: assets/font_mon/Montserrat-Medium.ttf

    - family: Montserrat-Regular
      fonts:
        - asset: assets/font_mon/Montserrat-Regular.ttf

    - family: Montserrat-SemiBold
      fonts:
        - asset: assets/font_mon/Montserrat-SemiBold.ttf

    - family: Montserrat-ExtraBold
      fonts:
        - asset: assets/font_mon/Montserrat-ExtraBold.ttf

    - family: 29ltbukrabold.ttf
      fonts:
        - asset: assets/fonts/29ltbukrabold.ttf
    - family: 29ltbukrabolditalic.ttf
      fonts:
         - asset: assets/fonts/29ltbukrabolditalic.ttf
    - family: 29ltbukralight.ttf
      fonts:
        - asset: assets/fonts/29ltbukralight.ttf
    - family: 29ltbukraregular.ttf
      fonts:
        - asset: assets/fonts/29ltbukraregular.ttf

    - family: BAUHAUSM.TTF
      fonts:
        - asset: assets/fonts/BAUHAUSM.TTF

    - family: BukraAlt_Medium.otf
      fonts:
        - asset: assets/fonts/BukraAlt_Medium.otf

    - family: calibri.ttf
      fonts:
        - asset: assets/fonts/calibri.ttf

    - family: calibrib.ttf
      fonts:
        - asset: assets/fonts/calibrib.ttf

    - family: calibrii.ttf
      fonts:
        - asset: assets/fonts/calibrii.ttf

    - family: calibril.ttf
      fonts:
        - asset: assets/fonts/calibril.ttf

    - family: calibrili.ttf
      fonts:
        - asset: assets/fonts/calibrili.ttf
    - family: calibriz.ttf
      fonts:
        - asset: assets/fonts/calibriz.ttf
    - family: FRADM.TTF
      fonts:
        - asset: assets/fonts/FRADM.TTF
    - family: FRADMCN.TTF
      fonts:
        - asset: assets/fonts/FRADMCN.TTF

    - family: FRADMIT.TTF
      fonts:
        - asset: assets/fonts/FRADMIT.TTF

    - family: FRAHV.TTF
      fonts:
        - asset: assets/fonts/FRAHV.TTF

    - family: FRAHVIT.TTF
      fonts:
        - asset: assets/fonts/FRAHVIT.TTF

    - family: framd.ttf
      fonts:
        - asset: assets/fonts/framd.ttf

    - family: FRAMDCN.TTF
      fonts:
        - asset: assets/fonts/FRAMDCN.TTF

    - family: framdit.ttf
      fonts:
        - asset: assets/fonts/framdit.ttf

    - family: majalla.ttf
      fonts:
        - asset: assets/fonts/majalla.ttf
    - family: majallab.ttf
      fonts:
        - asset: assets/fonts/majallab.ttf
